name: Use Secrets and Variables

on: push

jobs:
  show-variables:
    runs-on: ubuntu-latest
    env:
      MY_ENV_VAR: production
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Print Env Variable
        run: echo "Env is $MY_ENV_VAR"

      - name: Print Secret
        run: echo "The secret is ${{ secrets.MY_SECRET }}"
