name: Use Secrets and Vairiables

on: push

jobs:
  show-variables:
   runs-on: ubuntu-latest
   env:
    MY_ENV_VAR: production
   steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Print ENV Variables 
      uses: echo "Env is $MY_ENV_VAR"

    - name: Print Secrets
      uses: echo "The secret is"
